---
- name: "Configure Unit"
  hosts: localhost
  connection: local
  roles:
    - role: setup_dotfiles
      tags: dotfiles

    - role: install_packages
      tags: packages

    - role: setup_aur
      tags: paru

    - role: install_python
      tags: python

    - role: install_nvm
      tags: nvm

    - role: install_rust
      tags: rust

    # - role: install_astronvim
    #   tags: astronvim

    # - role: install_lazyvim
    #   tags: lazyvim

    # - role: install_fonts
    #   tags: fonts

