---
- name: "Configure Unit"
  hosts: localhost
  connection: local
  roles:

    - role: install_packages
      tags: packages

    - role: setup_dotfiles
      tags: dotfiles

    - role: install_python
      tags: python

    - role: install_rust
      tags: rust

    - role: install_go
      tags: go

    - role: install_node
      tags: node

    - role: setup_aur
      tags: paru

    # - role: install_astronvim
    #   tags: astronvim

    # - role: install_lazyvim
    #   tags: lazyvim

    # - role: install_fonts
    #   tags: fonts

    # - role: install_nvm
    #   tags: nvm

