---
# handlers file for setup_dotfiles
- name: checkout_dotfiles
  shell: |
    mkdir -p $HOME/playground/backup && mv $HOME/.{bash_profile,bashrc} $_
    /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME config --local status.showUntrackedFiles no
    /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout
