---
# tasks file for install_lazyvim
- name: "Install Lazyvim"
  tags: lazyvim
  ansible.builtin.git:
    repo: "git@github.com:Jobin-Nelson/lazyvim_config.git"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    update: true
