---
# tasks file for install_go
- name: "Install Go"
  import_tasks: archlinux.yml
  when: ansible_facts['os_family'] | lower == 'archlinux'

- name: "Install Ubuntu Packages"
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
