---
# tasks file for setup_dotfiles
- name: "Download Dotfiles"
  ansible.builtin.git:
    repo: git@github.com:Jobin-Nelson/.dotfiles.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    bare: true
    update: true
    depth: 5
    accept_hostkey: false
    key_file: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
  notify: checkout_dotfiles
