---
- name: "Install Archlinux Packages"
  become: true
  community.general.pacman:
    name:
      - git
      - man-db
      - man-pages
      - curl
      - unzip
      - tmux
      - zoxide
      - fzf
      - ripgrep
      - fd
      - nsxiv
      - jq
      - neovim
      - vim
      - alacritty
      - zathura
      - zathura-pdf-mupdf
      - mpv
      - tk
      - starship
      - docker
      - aria2
      - rsync
      - pacman-contrib
      - netcat
      - fastfetch
      - flatpak
      - ttf-jetbrains-mono-nerd
      - ttf-hack-nerd
      - ttf-meslo-nerd
      - ttf-sourcecodepro-nerd
      - ttf-cascadia-code-nerd
      - ttf-ubuntu-mono-nerd
      - ttf-roboto-mono-nerd
      - net-tools
    state: latest
    update_cache: true

- name: "Install Cronie"
  become: true
  community.general.pacman:
    name: cronie
    state: latest
  notify: start_cronie

- name: "Install Syncthing"
  become: true
  community.general.pacman:
    name: syncthing
    state: latest
  notify: start_syncthing

- name: "Install Flatpak Packages"
  community.general.flatpak:
    name:
      # - com.github.IsmaelMartinez.teams_for_linux
      # - com.github.tchx84.Flatseal
      # - org.gnome.Boxes
    state: present
