- name: Install the gpg key for nodejs LTS
  become: true
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Installing the nodejs LTS repos
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install the nodejs
  become: true
  ansible.builtin.apt:
    name: nodejs
    state: present
