---
# handlers file for install_packages
- name: start_cronie
  become: true
  ansible.builtin.service:
    name: cronie
    state: started
    enabled: yes

- name: start_syncthing
  become: true
  ansible.builtin.service:
    name: "syncthing@{{ ansible_env.USER }}"
    state: started
    enabled: yes

- name: start_docker
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: start_docker
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true
  
