---
# handlers file for install_packages
- name: start_cronie
  ansible.builtin.service:
    name: cronie
    state: started
    enabled: yes

- name: start_syncthing
  ansible.builtin.service:
    name: "syncthing@{{ ansible_env.USER }}"
    state: started
    enabled: yes
